services:
  db:
    image: postgres:16
    container_name: pickmovie-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pickmovie
      POSTGRES_PASSWORD: pickmovie_pw
      POSTGRES_DB: pickmovie_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
